name: misskey_auth_example
description: "Misskey Authライブラリの使用例"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.13.1 <4.0.0"
  flutter: ">=3.47.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  misskey_auth:
    path: ../
  http: ^1.6.0
  loader_overlay: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
