# .github/workflows/publish-on-tag.yml
name: Publish to pub.dev (on tag)

on:
  push:
    tags:
      - 'v*'   # pub.dev 側の tag-pattern 'v{{version}}' と揃える

jobs:
  publish:
    # OIDC 認証に必要
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      #  setup-dart が pub.dev への一時OIDCトークンを用意
      - uses: dart-lang/setup-dart@v1

      # 事前検証（dry run）
      - name: Dry run
        run: dart pub publish --dry-run

      # 本公開
      - name: Publish
        run: dart pub publish --force